name: excel_maping
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  csv: ^6.0.0
  drift: ^2.28.1
  drift_sqflite: ^2.0.1
  excel: ^4.0.6
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.4.1+1
  flutter_secure_storage: ^9.2.4
  http: ^1.5.0
  mobile_scanner: ^7.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  printing: ^5.14.2
  sqflite_sqlcipher: ^3.3.0

dev_dependencies:
  build_runner: ^2.7.1
  drift_dev: ^2.28.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  sqflite: any
